#CRIA BANCO NA RAIZ DO PROJETO
#spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

#POSTGRESQL CLIENT
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio-product-inventory-db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#EXECUTAR IMPORT.SQL - TEMPORARIO obs. none/create/update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true